Repository berenteb/bkk-nearby-departures, pull requests merged in 2021-04, with the labels that each got.

#32 Added meta tag
  client/index.html
Labels: enhancement

#33 Added/edited headers with charset
  client/script.js
  index.js
Labels: bug

#34 Middle alignment
  client/index.html
  client/style.css
Labels: enhancement

#37 Round alert icon
  client/script.js
  client/svg/alert_round.svg
  package-lock.json
  package.json
Labels: enhancement

#35 Add weather API, refactor CSS
  client/index.html
  client/script.js
  client/style.css
  index.js
  package-lock.json
  package.json
  weather.js
Labels: enhancement

#38 CSS improvements
  client/style.css
  package-lock.json
  package.json
Labels: enhancement

#40 EJS templating / Server side rendering
  README.md
  client/script.js
  client/svg/AIRPLANE.svg
  client/svg/BUS.svg
  client/svg/CHAIRLIFT.svg
  client/svg/FERRY.svg
  client/svg/RAIL.svg
  client/svg/SIKLO.svg
  client/svg/SUBWAY.svg
  client/svg/TRAM.svg
  client/svg/TROLLEYBUS.svg
  index.js
  package-lock.json
  package.json
  views/field.ejs
  views/svg/airplane.svg
  views/svg/alert.svg
  views/svg/alert_round.svg
  views/svg/bus.svg
  views/svg/chairlift.svg
  views/svg/ferry.svg
  views/svg/logo.svg
  views/svg/night-bus.svg
  views/svg/rail.svg
  views/svg/siklo.svg
  views/svg/subway.svg
  views/svg/tram.svg
  views/svg/trolleybus.svg
Labels: enhancement, refactoring

#41 Added manual refresh - just click the logo!
  client/index.html
  client/script.js
  client/style.css
  package-lock.json
  package.json
Labels: enhancement
